CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"AUTHOR_ID"	NVARCHAR2(50)		NOT NULL,
	"AUTHOR_NAME"	NVARCHAR2(30)		NOT NULL,
	"REPORT_REASON"	NVARCHAR2(100)		NOT NULL,
	"REPORT_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"POST_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호 인덱스(PK)';

COMMENT ON COLUMN "REPORT"."AUTHOR_ID" IS '글작성자아이디';

COMMENT ON COLUMN "REPORT"."AUTHOR_NAME" IS '글작성자닉네임';

COMMENT ON COLUMN "REPORT"."REPORT_REASON" IS '신고관련사유';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고일자';

COMMENT ON COLUMN "REPORT"."POST_NO" IS '글 번호(FK)';

COMMENT ON COLUMN "REPORT"."MEMBER_NO" IS '회원번호 인덱스(FK)';

CREATE TABLE "POST" (
	"POST_NO"	NUMBER		NOT NULL,
	"POST_TITLE"	NVARCHAR2(100)		NOT NULL,
	"POST_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"CATEGORY"	NVARCHAR2(7)		NOT NULL,
	"STATUS"	VARCHAR2(11)	DEFAULT 'NOT_START'	NOT NULL,
	"POST_DELETE"	VARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"POST_UPDATE"	TIMESTAMP		NULL,
	"VIEWS"	NUMBER	DEFAULT 0	NULL,
	"ADOPT_FEE"	NUMBER		NULL,
	"MISSING_DATE"	TIMESTAMP		NULL,
	"MISSING_TIME"	TIMESTAMP		NULL,
	"LOCATION"	NVARCHAR2(100)		NULL,
	"SPECIES"	VARCHAR2(3)	DEFAULT 'dog'	NOT NULL,
	"GENDER"	VARCHAR2(9)	DEFAULT 'M'	NOT NULL,
	"AGE"	NUMBER		NOT NULL,
	"WEIGHT"	NUMBER		NOT NULL,
	"CONTENT"	CLOB		NULL,
	"MENU_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "POST"."POST_NO" IS '글 번호(PK)';

COMMENT ON COLUMN "POST"."POST_TITLE" IS '글 제목';

COMMENT ON COLUMN "POST"."POST_DATE" IS '글 작성일';

COMMENT ON COLUMN "POST"."CATEGORY" IS '글 구분';

COMMENT ON COLUMN "POST"."STATUS" IS '상태 여부(NOT_START, IN_PROGRESS, COMPLETE)';

COMMENT ON COLUMN "POST"."POST_DELETE" IS '글 삭제 여부';

COMMENT ON COLUMN "POST"."POST_UPDATE" IS '글 수정일';

COMMENT ON COLUMN "POST"."VIEWS" IS '조회수';

COMMENT ON COLUMN "POST"."ADOPT_FEE" IS '입양비용';

COMMENT ON COLUMN "POST"."MISSING_DATE" IS '실종, 목격 날짜';

COMMENT ON COLUMN "POST"."MISSING_TIME" IS '실종, 목격 시간';

COMMENT ON COLUMN "POST"."LOCATION" IS '사건발생 위치';

COMMENT ON COLUMN "POST"."SPECIES" IS '동물 종 (dog,cat,etc)';

COMMENT ON COLUMN "POST"."GENDER" IS '성별 (M,F,neutering,unknown)';

COMMENT ON COLUMN "POST"."AGE" IS '나이';

COMMENT ON COLUMN "POST"."WEIGHT" IS '체중';

COMMENT ON COLUMN "POST"."CONTENT" IS '특징';

COMMENT ON COLUMN "POST"."MENU_NO" IS '게시판 번호(FK)';

COMMENT ON COLUMN "POST"."MEMBER_NO" IS '회원번호 인덱스(FK)';

CREATE TABLE "POST_KIND" (
	"MENU_NO"	NUMBER		NOT NULL,
	"MENU_NAME"	NVARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "POST_KIND"."MENU_NO" IS '게시판 번호(PK)';

COMMENT ON COLUMN "POST_KIND"."MENU_NAME" IS '게시판 이름';

CREATE TABLE "POST_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	NVARCHAR2(200)		NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(80)		NULL,
	"IMG_RENAME"	NVARCHAR2(80)		NULL,
	"POST_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "POST_IMG"."IMG_NO" IS '이미지 번호(PK)';

COMMENT ON COLUMN "POST_IMG"."IMG_PATH" IS '이미지 요청 경로';

COMMENT ON COLUMN "POST_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "POST_IMG"."IMG_RENAME" IS '이미지 변경명_글반호_이미지순서';

COMMENT ON COLUMN "POST_IMG"."POST_NO" IS '글 번호(FK)';

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"REPLY_TIME"	TIMESTAMP		NOT NULL,
	"REPLY_UPDATE"	TIMESTAMP		NULL,
	"REPLY_DELETE"	NVARCHAR2(1)	DEFAULT 'N'	NOT NULL,
	"POST_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글 번호(PK)';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "REPLY"."REPLY_TIME" IS '댓글 작성 시간';

COMMENT ON COLUMN "REPLY"."REPLY_UPDATE" IS '댓글 수정일';

COMMENT ON COLUMN "REPLY"."REPLY_DELETE" IS '댓글 삭제 여부';

COMMENT ON COLUMN "REPLY"."POST_NO" IS '글 번호(FK)';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호 인덱스(PK)';

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_NAME"	NVARCHAR2(30)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(20)		NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL,
	"PROFILE_IMG"	VARCHAR2(300)		NULL,
	"ENROLL_DATE"	TIMESTAMP	DEFAULT SYSTIMESTAMP	NOT NULL,
	"UPDATE_DATE"	TIMESTAMP		NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호 인덱스(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴여부';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '회원 권한';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."UPDATE_DATE" IS '회원 정보수정일';

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "POST" ADD CONSTRAINT "PK_POST" PRIMARY KEY (
	"POST_NO"
);

ALTER TABLE "POST_KIND" ADD CONSTRAINT "PK_POST_KIND" PRIMARY KEY (
	"MENU_NO"
);

ALTER TABLE "POST_IMG" ADD CONSTRAINT "PK_POST_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_POST_TO_REPORT_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "POST" (
	"POST_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "POST" ADD CONSTRAINT "FK_POST_KIND_TO_POST_1" FOREIGN KEY (
	"MENU_NO"
)
REFERENCES "POST_KIND" (
	"MENU_NO"
);

ALTER TABLE "POST" ADD CONSTRAINT "FK_MEMBER_TO_POST_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "POST_IMG" ADD CONSTRAINT "FK_POST_TO_POST_IMG_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "POST" (
	"POST_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_POST_TO_REPLY_1" FOREIGN KEY (
	"POST_NO"
)
REFERENCES "POST" (
	"POST_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

/* =====================================================
0. SEQUENCE (없으면 생성)
===================================================== */
CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST_KIND START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPLY START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_POST_IMG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPORT START WITH 1 INCREMENT BY 1 NOCACHE;

